import Head from "next/head";
import { useUser, SignOutButton } from "@clerk/nextjs";
import Image from "next/image";

export default function Home() {
  const { isSignedIn, user, isLoaded } = useUser();
  if (!isLoaded) {
    return null;
  }
  if (!isSignedIn) {
    return null;
  }
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <nav className="flex justify-between bg-white p-4">
        <div className="logo-container">
          <Image src="/logo.jpg" alt="Logo" width={60} height={60} />
        </div>
        <div className="flex items-center space-x-4">
          <div className="rounded-full overflow-hidden">
            {user?.profileImageUrl ? (
              <Image
                src={user?.profileImageUrl}
                alt="Profile Picture"
                width={50}
                height={50}
              />
            ) : (
              <Image
                src="/profileImg.png"
                alt="Profile Picture"
                width={50}
                height={50}
              />
            )}
          </div>
          <SignOutButton>
            <button className="rounded-md bg-yellow-200 px-4 py-2 text-xl text-black hover:bg-yellow-600 hover:text-white">
              Logout
            </button>
          </SignOutButton>
        </div>
      </nav>
      <main className="min-h-screen bg-slate-400"></main>
    </div>
  );
}
