import Head from "next/head";
import Link from "next/link";
import { SignIn } from "@clerk/nextjs";
import { api } from "~/utils/api";
import { useState } from "react";
import Image from "next/image";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const [isSignInVisible, setIsSignInVisible] = useState(false);

  const toggleSignIn = () => {
    setIsSignInVisible(!isSignInVisible);
  };

  return (
    <div className="min-h-screen">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-white p-4 flex justify-between">
  <div className="logo-container">
    <Image src="/logo.jpg" alt="Logo" width={60} height={60} />
  </div>


        <button
          onClick={toggleSignIn}
          className="bg-yellow-300 text-white px-4 py-2 text-xl rounded-md hover:bg-yellow-700"
        >
          Sign In
        </button>
      </nav>
      <main className="min-h-screen bg-slate-400">
        <div className="flex h-full items-center justify-center">
          {isSignInVisible ? (
            <div className="bg-white p-4 rounded-lg">
              <SignIn />
            </div>
          ) : null}
          {isSignInVisible && (
            <div
              className="fixed inset-0 bg-gray-500 opacity-50 z-10"
              onClick={toggleSignIn}
            ></div>
          )}
        </div>
      </main>
    </div>
  );
}
